development:
  clients:
    default:
      database: pgm-prod
      hosts:
        - mongo:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: pgm-prod
      hosts:
        - mongo:38128
  options:
    raise_not_found_error: false

staging:
  clients:
    default:
      database: pgm-prod
      hosts:
        - mongo:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: pgm-prod
      hosts:
        - mongo:27017
  options:
    raise_not_found_error: false
